-- PayGuard Database Schema
-- Generated for Phase 2 (Step 3)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ENUM types
CREATE TYPE user_role AS ENUM ('ANALYST', 'ADMIN');
CREATE TYPE alert_decision AS ENUM ('APPROVE', 'REVIEW', 'BLOCK');
CREATE TYPE alert_status AS ENUM ('OPEN', 'IN_REVIEW', 'RESOLVED');
CREATE TYPE severity_level AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE verdict_type AS ENUM ('FRAUD', 'LEGITIMATE');

-- =========================
-- users
-- =========================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'ANALYST',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE users IS 'Analyst and Admin accounts for dashboard access';

-- =========================
-- transactions
-- =========================
CREATE TABLE transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id VARCHAR(100) UNIQUE NOT NULL,
    account_id VARCHAR(100) NOT NULL,
    amount NUMERIC(15,2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'INR',
    device_id VARCHAR(100),
    location VARCHAR(100),
    merchant_type VARCHAR(100),
    transaction_timestamp TIMESTAMPTZ NOT NULL,
    is_fraud BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE transactions IS 'Raw incoming transactions';
COMMENT ON COLUMN transactions.is_fraud IS 'Ground truth label, used for dataset/simulation only, not supplied by production requests';

-- Required for fast behavioral lookups (velocity, avg amount, etc.)
CREATE INDEX idx_transactions_account_time
    ON transactions(account_id, transaction_timestamp);

CREATE INDEX idx_transactions_timestamp
    ON transactions(transaction_timestamp);

CREATE INDEX idx_transactions_account_device
    ON transactions(account_id, device_id);

CREATE INDEX idx_transactions_account_location
    ON transactions(account_id, location);

-- =========================
-- transaction_features
-- =========================
CREATE TABLE transaction_features (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id UUID NOT NULL UNIQUE REFERENCES transactions(id) ON DELETE CASCADE,
    transactions_last_2_min INTEGER,
    transactions_last_1_hour INTEGER,
    account_avg_amount NUMERIC(15,2),
    amount_ratio NUMERIC(10,4),
    time_since_previous_transaction_seconds BIGINT,
    new_device BOOLEAN,
    new_location BOOLEAN,
    transaction_hour SMALLINT CHECK (transaction_hour BETWEEN 0 AND 23),
    odd_hour BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE transaction_features IS 'Derived behavioral/contextual features computed at request time from transactions history';

-- =========================
-- alerts
-- =========================
CREATE TABLE alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id UUID NOT NULL UNIQUE REFERENCES transactions(id) ON DELETE CASCADE,
    fraud_probability NUMERIC(5,4) CHECK (fraud_probability BETWEEN 0 AND 1),
    rule_score NUMERIC(5,4),
    final_score NUMERIC(5,4),
    decision alert_decision NOT NULL,
    severity severity_level,
    status alert_status NOT NULL DEFAULT 'OPEN',
    explanation JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE alerts IS 'Alerts generated by the hybrid decision engine';
COMMENT ON COLUMN alerts.explanation IS 'SHAP reasons and rule triggers, stored as JSON';

CREATE INDEX idx_alerts_status ON alerts(status);
CREATE INDEX idx_alerts_decision ON alerts(decision);
CREATE INDEX idx_alerts_created_at ON alerts(created_at);

-- =========================
-- analyst_verdicts
-- =========================
CREATE TABLE analyst_verdicts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    alert_id UUID NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
    analyst_id UUID NOT NULL REFERENCES users(id),
    verdict verdict_type NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE analyst_verdicts IS 'Analyst feedback on alerts, used as ground truth for retraining';

CREATE INDEX idx_analyst_verdicts_alert ON analyst_verdicts(alert_id);

-- =========================
-- audit_logs
-- =========================
CREATE TABLE audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100),
    entity_id VARCHAR(100),
    details JSONB,
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE audit_logs IS 'System-wide audit trail for security and compliance';

CREATE INDEX idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);

-- =========================
-- model_versions
-- =========================
CREATE TABLE model_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    version VARCHAR(50) UNIQUE NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    algorithm VARCHAR(50) NOT NULL,
    metrics JSONB,
    model_path VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE model_versions IS 'Metadata for trained ML models; the model artifact itself lives in the FastAPI model_store, not the database';
