import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { getDashboardSummary } from '../api/dashboard';

export const OverviewPage: React.FC = () => {
  const {
    data: summary,
    isLoading,
    isError,
    error,
    refetch,
    isFetching,
  } = useQuery({
    queryKey: ['dashboardSummary', 24],
    queryFn: () => getDashboardSummary(24),
    refetchInterval: 30000,
  });

  const formatDate = (dateStr?: string) => {
    if (!dateStr) return '—';
    try {
      const d = new Date(dateStr);
      return d.toLocaleString('en-US', {
        year: 'numeric',
        month: 'short',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: false,
      });
    } catch {
      return dateStr;
    }
  };

  const formatPercentage = (rate: number | null) => {
    if (rate === null || rate === undefined || isNaN(rate)) {
      return 'N/A (no alerts in window)';
    }
    const pct = rate * 100;
    return `${pct % 1 === 0 ? pct.toFixed(0) : pct.toFixed(1)}%`;
  };

  if (isLoading) {
    return (
      <div className="table-container" style={{ minHeight: '350px' }}>
        <div className="loading-container">
          <span className="spinner" style={{ width: '32px', height: '32px' }} />
          <span>Loading overview statistics...</span>
        </div>
      </div>
    );
  }

  if (isError) {
    return (
      <div className="error-banner">
        <div>
          <strong>Error loading dashboard summary:</strong> {error instanceof Error ? error.message : 'Unknown error'}
        </div>
        <button onClick={() => refetch()} className="btn btn-secondary btn-sm">
          Retry
        </button>
      </div>
    );
  }

  if (!summary) {
    return null;
  }

  const { decisionCounts, statusCounts, severityCounts, windowed } = summary;

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--text-primary)' }}>
            System Overview
          </h1>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
            Real-time fraud metrics, aggregate alert counts, and windowed telemetry
          </p>
        </div>
        {isFetching && !isLoading && (
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
            <span className="spinner" style={{ width: '14px', height: '14px', borderWidth: '2px' }} />
            <span>Updating...</span>
          </div>
        )}
      </div>

      {/* Row 1: High-Level Totals & Decision Cards */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '16px'
      }}>
        {/* Total Transactions */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div style={{ fontSize: '0.8125rem', fontWeight: '600', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
            Total Transactions
          </div>
          <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--text-primary)', marginTop: '8px' }}>
            {summary.totalTransactions.toLocaleString()}
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
            All-time processed
          </div>
        </div>

        {/* Total Alerts */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div style={{ fontSize: '0.8125rem', fontWeight: '600', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
            Total Alerts
          </div>
          <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--text-primary)', marginTop: '8px' }}>
            {summary.totalAlerts.toLocaleString()}
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
            Generated by rules & ML
          </div>
        </div>

        {/* APPROVE Card */}
        <div className="card" style={{
          borderLeft: '4px solid var(--color-green-text)',
          backgroundColor: 'var(--bg-surface)'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '0.8125rem', fontWeight: '600', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
              Approve
            </span>
            <span className="badge badge-approve" style={{ fontSize: '0.65rem' }}>Decision</span>
          </div>
          <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--color-green-text)', marginTop: '8px' }}>
            {decisionCounts.approve.toLocaleString()}
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
            Clean transactions
          </div>
        </div>

        {/* REVIEW Card */}
        <div className="card" style={{
          borderLeft: '4px solid var(--color-amber-text)',
          backgroundColor: 'var(--bg-surface)'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '0.8125rem', fontWeight: '600', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
              Review
            </span>
            <span className="badge badge-review" style={{ fontSize: '0.65rem' }}>Decision</span>
          </div>
          <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--color-amber-text)', marginTop: '8px' }}>
            {decisionCounts.review.toLocaleString()}
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
            Under investigation
          </div>
        </div>

        {/* BLOCK Card */}
        <div className="card" style={{
          borderLeft: '4px solid var(--color-red-text)',
          backgroundColor: 'var(--bg-surface)'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '0.8125rem', fontWeight: '600', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
              Block
            </span>
            <span className="badge badge-block" style={{ fontSize: '0.65rem' }}>Decision</span>
          </div>
          <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--color-red-text)', marginTop: '8px' }}>
            {decisionCounts.block.toLocaleString()}
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
            High-risk blocked
          </div>
        </div>
      </div>

      {/* Row 2: Secondary Breakdown (Status & Severity) */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))',
        gap: '16px'
      }}>
        {/* Status Counts */}
        <div className="card">
          <h2 style={{ fontSize: '1rem', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '16px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px' }}>
            Alert Status Breakdown
          </h2>
          <div style={{ display: 'flex', justifyContent: 'space-around', alignItems: 'center', textAlign: 'center', paddingTop: '8px' }}>
            <div>
              <span className="badge badge-open" style={{ marginBottom: '8px' }}>OPEN</span>
              <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--text-primary)', marginTop: '4px' }}>
                {statusCounts.open.toLocaleString()}
              </div>
            </div>
            <div style={{ width: '1px', height: '40px', backgroundColor: 'var(--border-color)' }} />
            <div>
              <span className="badge badge-in_review" style={{ marginBottom: '8px' }}>IN_REVIEW</span>
              <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--text-primary)', marginTop: '4px' }}>
                {statusCounts.inReview.toLocaleString()}
              </div>
            </div>
            <div style={{ width: '1px', height: '40px', backgroundColor: 'var(--border-color)' }} />
            <div>
              <span className="badge badge-resolved" style={{ marginBottom: '8px' }}>RESOLVED</span>
              <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--text-primary)', marginTop: '4px' }}>
                {statusCounts.resolved.toLocaleString()}
              </div>
            </div>
          </div>
        </div>

        {/* Severity Counts */}
        <div className="card">
          <h2 style={{ fontSize: '1rem', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '16px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px' }}>
            Alert Severity Breakdown
          </h2>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', textAlign: 'center', paddingTop: '8px', flexWrap: 'wrap', gap: '8px' }}>
            <div style={{ flex: 1, minWidth: '60px' }}>
              <span className="badge badge-low">LOW</span>
              <div style={{ fontSize: '1.25rem', fontWeight: '700', color: 'var(--text-primary)', marginTop: '4px' }}>
                {severityCounts.low}
              </div>
            </div>
            <div style={{ flex: 1, minWidth: '60px' }}>
              <span className="badge badge-medium">MED</span>
              <div style={{ fontSize: '1.25rem', fontWeight: '700', color: 'var(--text-primary)', marginTop: '4px' }}>
                {severityCounts.medium}
              </div>
            </div>
            <div style={{ flex: 1, minWidth: '60px' }}>
              <span className="badge badge-high">HIGH</span>
              <div style={{ fontSize: '1.25rem', fontWeight: '700', color: 'var(--text-primary)', marginTop: '4px' }}>
                {severityCounts.high}
              </div>
            </div>
            <div style={{ flex: 1, minWidth: '60px' }}>
              <span className="badge badge-critical">CRIT</span>
              <div style={{ fontSize: '1.25rem', fontWeight: '700', color: 'var(--text-primary)', marginTop: '4px' }}>
                {severityCounts.critical}
              </div>
            </div>
            <div style={{ flex: 1, minWidth: '60px' }}>
              <span className="badge" style={{ backgroundColor: 'var(--bg-surface-elevated)', color: 'var(--text-muted)' }}>UNCL</span>
              <div style={{ fontSize: '1.25rem', fontWeight: '700', color: 'var(--text-secondary)', marginTop: '4px' }}>
                {severityCounts.unclassified}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Row 3: Windowed Stats (Last 24 Hours) */}
      <div className="card">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px', marginBottom: '16px', borderBottom: '1px solid var(--border-color)', paddingBottom: '10px' }}>
          <h2 style={{ fontSize: '1.125rem', fontWeight: '600', color: 'var(--text-primary)' }}>
            Recent Activity (Last 24 Hours)
          </h2>
          <div style={{ fontSize: '0.8125rem', color: 'var(--text-muted)' }}>
            Window boundary since: <span className="monospace" style={{ color: 'var(--text-secondary)' }}>{formatDate(windowed.sinceTimestamp)}</span>
          </div>
        </div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
          gap: '16px'
        }}>
          {/* Transactions in window */}
          <div style={{ backgroundColor: 'var(--bg-surface-elevated)', padding: '16px', borderRadius: '6px' }}>
            <div style={{ fontSize: '0.75rem', fontWeight: '600', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
              Transactions in Window
            </div>
            <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--text-primary)', marginTop: '6px' }}>
              {windowed.transactionsInWindow.toLocaleString()}
            </div>
          </div>

          {/* Alerts in window */}
          <div style={{ backgroundColor: 'var(--bg-surface-elevated)', padding: '16px', borderRadius: '6px' }}>
            <div style={{ fontSize: '0.75rem', fontWeight: '600', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
              Alerts in Window
            </div>
            <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--text-primary)', marginTop: '6px' }}>
              {windowed.alertsInWindow.toLocaleString()}
            </div>
          </div>

          {/* Review in window */}
          <div style={{ backgroundColor: 'var(--bg-surface-elevated)', padding: '16px', borderRadius: '6px' }}>
            <div style={{ fontSize: '0.75rem', fontWeight: '600', color: 'var(--color-amber-text)', textTransform: 'uppercase' }}>
              Review Alerts
            </div>
            <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--color-amber-text)', marginTop: '6px' }}>
              {windowed.reviewCountInWindow.toLocaleString()}
            </div>
          </div>

          {/* Block in window */}
          <div style={{ backgroundColor: 'var(--bg-surface-elevated)', padding: '16px', borderRadius: '6px' }}>
            <div style={{ fontSize: '0.75rem', fontWeight: '600', color: 'var(--color-red-text)', textTransform: 'uppercase' }}>
              Block Alerts
            </div>
            <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--color-red-text)', marginTop: '6px' }}>
              {windowed.blockCountInWindow.toLocaleString()}
            </div>
          </div>

          {/* ML Availability Rate */}
          <div style={{ backgroundColor: 'var(--bg-surface-elevated)', padding: '16px', borderRadius: '6px' }}>
            <div style={{ fontSize: '0.75rem', fontWeight: '600', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
              ML Availability Rate
            </div>
            <div style={{
              fontSize: summary.mlAvailabilityRate !== null ? '1.5rem' : '1rem',
              fontWeight: '700',
              color: summary.mlAvailabilityRate !== null ? 'var(--color-green-text)' : 'var(--text-muted)',
              marginTop: '6px'
            }}>
              {formatPercentage(summary.mlAvailabilityRate)}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
